 version: 2.1

 orbs:
  win: circleci/windows@2.2.0

 jobs:
   build:
     executor: win/default     
    
     steps:
        - checkout
        - run: dotnet build -c Release
        - run:
            name: Test
            command: ls
        - run:
            name: Compress Artifacts
            command: Compress-Archive .\Release\net5.0\* .\SFMLRaycaster.zip
        - store_artifacts:
            path: .\SFMLRaycaster.zip