 version: 2.1
 orbs:
  win: circleci/windows@2.2.0
  github-release: h-matsuo/github-release@0.1.3
 jobs:
   build:
     executor: win/default
     steps:
        - checkout
        - run: dotnet build -c Release
        - run:
            name: Compress Artifacts
            command: Compress-Archive .\Release\net5.0\* .\SFMLRaycaster.zip
        - github-release/create:
            tag: latest
            title: Version latest
            description: This release is version latest.
            file-path: .\SFMLRaycaster.zip
        