 version: 2.1

 orbs:
  win: circleci/windows@2.2.0

 jobs:
   build:
     executor: win/default     
    
     steps:
        - checkout
        - run: dotnet build
        - run: apt-get install -y zip
        - run:
            name: Compress Artifacts
            command: zip -r SFMLRaycaster.zip ./Release/net5.0/*
        - store_artifacts:
            path: ./SFMLRaycaster.zip